// TODO: Dynamically create/store this list in Rails from the
// set of all roles from all people
export const ROLES = [
  'Any',
  'Account Managment',
  'Account Manager',
  'analytics',
  'Android',
  'AngularJS',
  'Back End Drupal Engineer',
  'Billable FTE',
  'Brave One Agency',
  'business development',
  'Chomoka',
  'Content Strategy',
  'Design',
  'Design Team',
  'Django',
  "don't staff",
  'Drupal',
  'Engineering',
  'Engineering Team',
  'finance',
  'Front End Drupal Engineer',
  'FTE',
  'iOS',
  'Javascript',
  'Kalamuna',
  'Lowercase Productions',
  'Luksic',
  'metrics',
  'Mobile Engineer',
  'Partner',
  'PHP',
  'PM',
  'PO',
  'Product Manager',
  'Product Team',
  'Project Management',
  'QA',
  'Rails',
  'React',
  'Research',
  'Research/Testing',
  'Ruby',
  'SFUSD',
  'Tableau',
  'UI',
  'UI Designer',
  'UX',
  'Visual Designer',
  'WordPress'
]